development:
  adapter: postgresql
  encoding: unicode
  database: project_x
  pool: 5
  username: user
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: project_x
  pool: 5
  username: user
  password:
